kind: Deployment
apiVersion: apps/v1
metadata:
  name: bff-deployment
  labels:
    app: bff
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bff
  template:
    metadata:
      labels:
        app: bff
    spec:
      containers:
        - name: bff
          image: vehicle-bff:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4000
          env:
            - name: NODE_ENV
              value: production
            - name: KAFKA
              value: kafka.kafka:9092